server:
  port: 10000

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.119.1:8848
        username: nacos
        password: nacos
        service: ${spring.application.name}

    gateway:
      routes:
        #将路径为Path=/api/thirdparty/**转发至第三方服务模块
        - id: third_party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/product转发product微服务
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/member/**转发至会员服务
        - id: member_route
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/ware/**转发至仓库服务
        - id: ware_route
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/coupon/**转发至优惠服务

        - id: coupon_route
          uri: lb://coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/**转发至后台管理
        - id: admin_route
          uri: lb://admin
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将主机地址为search.yeeph.com转发至search
        - id: search_host
          uri: lb://search
          predicates:
            - Host=search.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /auth/$\{segment}

        #将主机地址为auth.yeeph.com转发至auth
        - id: auth_host
          uri: lb://auth
          predicates:
            - Host=auth.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /auth/$\{segment}

        #将主机地址为search.yeeph.com转发至search
        - id: cart_host
          uri: lb://cart
          predicates:
            - Host=cart.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /cart/$\{segment}

        #将主机地址为order.yeeph.com转发至order
        - id: order_host
          uri: lb://order
          predicates:
            - Host=order.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /order/$\{segment}

        #将主机地址为seckill.yeeph.com转发至seckill
        - id: seckill_host
          uri: lb://seckill
          predicates:
            - Host=seckill.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /seckill/$\{segment}

        #将主机地址为**.yeeph.com转发至product
        - id: product_host
          uri: lb://product
          predicates:
            - Host=**.yeeph.com:10000
          filters:
            - RewritePath=/(?<segment>.*), /product/$\{segment}

#    sentinel:
#      transport:
#        dashboard: localhost:8080
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#    #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.loadbalancer: trace
    org.springframework.web.reactive: trace



