server:
  port: 17000
  servlet:
    context-path: /search

spring:
  application:
    name: search

  redis:
    host: 192.168.119.129
    password: nopwd
  session:
    store-type: redis

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.119.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#  #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1
logging:
  level:
    io.niceseason.gulimall.search.service: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'