server:
  port: 11000
  servlet:
    session:
      timeout: 30m
    context-path: /auth

spring:
  application:
    name: auth

  mail:
    host: smtp.qq.com
    username: 3462401590@qq.com
    password: mwmfirlopciwcjfd
    port: 465
    protocol: smtps
    default-encoding: utf-8
    properties:
      mail:
        stmp:
          ssl:
            enable: true

  redis:
    host: 192.168.119.129
    password: nopwd
  session:
    store-type: redis

  cloud:
    nacos:
      discovery: #服务注册和发现中心
        server-addr: 192.168.119.1:8848
        username: nacos
        password: nacos
        service: ${spring.application.name}


#    sentinel:
#      transport:
#        dashboard: localhost:8080

#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: web
#    discovery-client-enabled: false
#  #采样取值介于 0到1之间，1则表示全部收集
#  sleuth:
#    sampler:
#      probability: 1

snowflake:
  dataCenterId: 0
  workerId: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'


