server:
  port: 13000
  servlet:
    context-path: /coupon

spring:
  application:
    name: coupon

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.119.129:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
      maximum-pool-size: 20

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.119.1:8848


  #  # jackson时间格式化
  jackson:
    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  mvc:
#    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS Z

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.yeeph.coupon.dao: debug


management:
  endpoints:
    web:
      exposure:
        include: '*'

coupon:
  user:
    name: zhangsan
    age: 15